defaults:
  - _self_
  - datamodule: debug_dataset
  - trainer: default_trainer
  - training: default_training
  - logging: comet_ml
  - optimizer: adamw
  - scheduler: plateau
  - model: simple_model
  - callbacks: callbacks
  - private: custom
  - augmentation: basic_augs
  - loss: bce_logits
  - metric: metric_manager
  - inference: basic
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

general:
  logs_folder_name: logs
  workspace: thurs8
  project_name: epigenetic-feature-prediction
  device: cuda
  log_code: False
  save_pytorch_model: True
  save_best: True
  convert_to_jit: True

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S} #_${hydra.job.override_dirname}
  sweep:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
