defaults:
  - _self_
  - datamodule: rte_datamodule
  - trainer: trainer
  - training: roberta_training
  - logging: comet_ml
  - optimizer: adamw
  - scheduler: linear_schedule_with_warmup
  - model: roberta
  - callbacks: callbacks
  - private: comet_api
#  - augmentation: basic_augs
  - loss: cross_entropy
  - metrics: accuracy
  - inference: basic
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

general:
  logs_folder_name: logs
  workspace: thurs88
  project_name: superglue
  device: cuda
  log_code: False
  save_pytorch_model: True
  save_best: True
  convert_to_jit: True

hydra:
  run:
    dir: ../outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ../outputs/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
